# Generated by Django 5.2.1 on 2025-05-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='Category Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Category Slug')),
                ('slug_tr', models.SlugField(null=True, unique=True, verbose_name='Category Slug')),
                ('slug_en', models.SlugField(null=True, unique=True, verbose_name='Category Slug')),
            ],
        ),
    ]
