# Generated by Django 5.2.1 on 2025-05-30 10:31

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tags Name')),
                ('name_tr', models.CharField(max_length=50, null=True, verbose_name='Tags Name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Tags Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Tags Slug')),
                ('slug_tr', models.SlugField(null=True, unique=True, verbose_name='Tags Slug')),
                ('slug_en', models.SlugField(null=True, unique=True, verbose_name='Tags Slug')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Post Content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Post Content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Post Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Post Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(to='blog.tags'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags_en',
            field=models.ManyToManyField(null=True, to='blog.tags'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags_tr',
            field=models.ManyToManyField(null=True, to='blog.tags'),
        ),
    ]
